// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASxcL3NldlsK1cTtoCwH2_PjiAVU0Avyk',
    appId: '1:253628741321:web:64d46a688788e7ea89ff18',
    messagingSenderId: '253628741321',
    projectId: 'deskly-app-98b01',
    authDomain: 'deskly-app-98b01.firebaseapp.com',
    storageBucket: 'deskly-app-98b01.firebasestorage.app',
    measurementId: 'G-BBY6P4YB3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGy3ByZo9UvSl7aslV8fCvT5x7ynRC29k',
    appId: '1:253628741321:android:1d9b154f36d607f489ff18',
    messagingSenderId: '253628741321',
    projectId: 'deskly-app-98b01',
    storageBucket: 'deskly-app-98b01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCbZMfWX6YI2sj5cZwxrf17PwlvHyATCM',
    appId: '1:253628741321:ios:774f055181d5ee8089ff18',
    messagingSenderId: '253628741321',
    projectId: 'deskly-app-98b01',
    storageBucket: 'deskly-app-98b01.firebasestorage.app',
    iosBundleId: 'com.example.desklyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCbZMfWX6YI2sj5cZwxrf17PwlvHyATCM',
    appId: '1:253628741321:ios:774f055181d5ee8089ff18',
    messagingSenderId: '253628741321',
    projectId: 'deskly-app-98b01',
    storageBucket: 'deskly-app-98b01.firebasestorage.app',
    iosBundleId: 'com.example.desklyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASxcL3NldlsK1cTtoCwH2_PjiAVU0Avyk',
    appId: '1:253628741321:web:43ffff35b09cdc5089ff18',
    messagingSenderId: '253628741321',
    projectId: 'deskly-app-98b01',
    authDomain: 'deskly-app-98b01.firebaseapp.com',
    storageBucket: 'deskly-app-98b01.firebasestorage.app',
    measurementId: 'G-4SLJ0X75DL',
  );
}
