// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:deskly_app/features/home/data/model/category_model/category_cache_model.dart';
import 'package:deskly_app/features/home/data/model/user_model/user_cache_model.dart';
import 'package:deskly_app/features/home/data/model/workspace_model/workspace_cahce_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryCacheModelAdapter());
    registerAdapter(UserCacheModelAdapter());
    registerAdapter(WorkspaceCacheModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryCacheModelAdapter());
    registerAdapter(UserCacheModelAdapter());
    registerAdapter(WorkspaceCacheModelAdapter());
  }
}
